[local_phases]
unit = "rspec spec/"
lint = 'echo skipping'
syntax = "echo skipping"
provision = "chef exec kitchen create"
deploy = "echo skipping"
smoke = "echo skipping"
functional = "echo skipping"
cleanup = "echo skipping"
